name: YT-DLP Workflow

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时自动执行

jobs:
  download_video:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Set up cookies.txt
        run: |
          echo "${{ secrets.YT_COOKIES }}" > cookies.txt  # 使用 GitHub Secrets 存储 cookies

      - name: Run yt-dlp to get live stream URL
        run: |
          yt-dlp --cookies cookies.txt https://www.youtube.com/watch?v=vr3XyVCR4T0
