name: Run yt-dlp Script

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-yt-dlp:
    runs-on: ubuntu-latest  # 在最新版本的 Ubuntu 上运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 将代码检出到 runner

      - name: Set up Python
        uses: actions/setup-python@v4  # 设置 Python 环境
        with:
          python-version: '3.x'  # 使用 Python 3.x 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖

      - name: Run yt-dlp script
        run: |
          python get_live_stream_url.py  # 运行你的 Python 脚本
